inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - spec/**/*
    - .bundle/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - log/**/*
    - Rakefile
    - bc-lightstep-ruby.gemspec

Lint/AmbiguousOperator:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
