language: ruby
cache:
  bundler: true
sudo: false
dist: trusty
rvm:
  - 2.4
  - 2.5
bundler_args: --without production
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
script: ./.travis.sh
env:
  matrix:
    - TEST_GROUP=prereq
    - TEST_GROUP=1
matrix:
  fast_finish: true
